spring.application.name=envios-express-backend

server.port=8080

# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/envios_express
spring.datasource.username=postgres
spring.datasource.password=Sebastian2004
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT AHÍ HAY UNA CLAVE ALEATORIA EN EL SECRET
app.jwt.secret=3xQ#8NwP!2LvZ7rKm@5HcDf9Ty$UaB6JsEp1MnRq%4VkXi&0FgYzLpW2oHsC7De
app.jwt.expiration-ms=86400000

# Logging
logging.level.com.enviosexpress=DEBUG
logging.level.org.springframework.security=INFO

# Habilitar logs detallados para Web y Swagger
logging.level.org.springframework.web=DEBUG
logging.level.org.springdoc=DEBUG